"""Add token system and subscription tiers

Revision ID: 010a0a92691c
Revises: 4669afefd283
Create Date: 2026-01-17 14:35:51.814693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010a0a92691c'
down_revision: Union[str, Sequence[str], None] = '4669afefd283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('cost_usd', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('response_time', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('subscription_tier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tokens_used_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tokens_limit_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_token_reset', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('total_spent_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_spent_usd')
    op.drop_column('users', 'last_token_reset')
    op.drop_column('users', 'tokens_limit_month')
    op.drop_column('users', 'tokens_used_month')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('messages', 'response_time')
    op.drop_column('messages', 'cost_usd')
    op.drop_column('messages', 'output_tokens')
    op.drop_column('messages', 'input_tokens')
    op.drop_column('messages', 'tokens_used')
    # ### end Alembic commands ###
